{{- if .Values.backend.postgres.sslsecret.name }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-tls-init
data:
  init.sh: |
    #!/bin/sh
    cp /ca.crt /client.crt /client.key /postgres-tls
    chmod 0400 /postgres-tls/*
    chown -R 65534:65534 /postgres-tls
{{ end }}
