{{- if and (eq .Values.autoscaling.enable true) (include "bindplane.deployment_type" .) "Deployment" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bindplane.fullname" . }}
spec:
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bindplane.fullname" . }}
  metrics:
{{- with .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- with .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
{{- end }}
{{- end }}
