{{- if eq (include "bindplane.deployment_type" .) "StatefulSet" }}
{{- if and (.Values.prometheus.enable) (.Values.prometheus.enableSideCar) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bindplane.fullname" . }}-prometheus-config
  labels:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prometheus.yml: |
    scrape_configs: []
    rule_files: [/etc/prometheus/rules.yml]
  rules.yml: |
    groups:
    - name: configuration-rollups
      interval: 1m
      rules:
      - record: bindplane_agent_measurements:rollup:rate:1m
        expr: sum without (agent) (rate(bindplane_agent_measurements{}[1m9s999ms] offset 10s))
  web.yml: |
    # web.yml is empty but must be present for Prometheus to start
{{- end }}
{{- end }}

