apiVersion: v1
kind: Service
metadata:
  name: {{ include "bindplane.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
{{- if eq .Values.eventbus.type "nats" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bindplane.fullname" . }}-nats-cluster-headless
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 6222
      protocol: TCP
      targetPort: nats-cluster
      name: nats-cluster
  selector:
    app.kubernetes.io/name: {{ include "bindplane.name" . }}
    app.kubernetes.io/stack: bindplane
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
{{- end }}
