name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm Check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/bindplane
          CHART_VALUES: ./charts/bindplane/values.yaml

  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm Docs
        run: |
          curl -L -o helm-docs.deb https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_arm64.deb
          sudo apt-get install -f ./helm-docs.deb

      - name: Update Docs
        run: helm-docs
      
      - name: Assert No Diff
        run: bash .github/workflows/scripts/assert-no-diff.sh 

  integration:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 3
      matrix:
        case:
          - "default"
          - "all"
          - "image"
          - "ingress"
        k8s_version:
          - v1.24.0
          - v1.25.0
          - v1.26.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          cache: true
          kubernetes-version: ${{ matrix.k8s_version }}
          addons: default-storageclass,storage-provisioner,ingress

      - name: Wait For Ingress Pods
        run: |
          sleep 5
          kubectl -n ingress-nginx wait deployment ingress-nginx-controller --timeout=120s --for condition=Available=True
          sleep 30
          kubectl -n ingress-nginx get all

      - name: Deploy
        run: |
          helm template \
            --values test/cases/${{ matrix.case }}/values.yaml \
            charts/bindplane | \
            ./kubectl apply -f -

      - name: Wait For Pods
        run: |
          sleep 15
          kubectl -n default get all
          kubectl -n default logs pod/release-name-bindplane-0
          kubectl -n default wait --for=condition=ready pods --all --timeout=120s
