name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm Check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/bindplane
          CHART_VALUES: ./charts/bindplane/values.yaml

  integration:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        case:
          - "default"
        k8s_version:
          - v1.24.0
          - v1.25.0
          - v1.26.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Inspec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

      - name: Install Inspec Plugins
        run: | 
          inspec plugin install train-kubernetes
          inspec plugin install inspec-k8s
        env:
          CHEF_LICENSE: accept-no-persist

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          cache: true
          kubernetes-version: ${{ matrix.k8s_version }}
          addons: default-storageclass,storage-provisioner,ingress

      - name: Deploy
        run: |
          helm template \
            --values test/cases/${{ matrix.case }}/values.yaml \
            charts/bindplane | \
            ./kubectl apply -f -

      - name: Wait For Pods
        run: kubectl -n default wait --for=condition=ready pods --all --timeout=120s

      - name: Test
        run: inspec exec cases/${{ matrix.case }}/inspec.rb
        working-directory: test/
        env:
          CHEF_LICENSE: accept-no-persist
