name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm Check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/bindplane
          CHART_VALUES: ./charts/bindplane/values.yaml
