name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  helm:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Helm Check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/bindplane
          CHART_VALUES: ./charts/bindplane/values.yaml

  integration:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        case:
          - "default"
        k8s_version:
          - v1.24.0
          - v1.25.0
          - v1.26.0

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cinc (Inspec)
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | \
          sudo bash -s -- -P cinc-auditor -v 4

      - run: sudo gem install k8s-client -v 0.10.4
      - run: sudo gem install train-kubernetes
      - run: inspec plugin install train-kubernetes

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          cache: true
          kubernetes-version: ${{ matrix.k8s_version }}

      - name: Deploy
        run: |
          helm template \
            --values test/cases/${{ matrix.case }}/values.yaml \
            charts/bindplane | \
            ./kubectl apply -f -

      - name: Get All
        run: sleep 10 && kubectl -n default get all

      - name: Wait For Pods
        run: kubectl -n default wait --for=condition=ready pods --all --timeout=120s